// URL'S

export const AUTH_API_URL = process.env.REACT_APP_AUTH_API_URL;

// // GENERATE RANDOM TOKEN
// export const GENERATE_ITEM_RANDOM =
//   process.env.REACT_APP_GENERATE_SECRET_KEY_TOKEN;

// <------- CONSTANTES DE USUARIOS ------->

// REGISTER

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

// LOGIN
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// FORGOT
export const INVALID_EMAIL = "INVALID_EMAIL";
export const VALID_EMAIL = "VALID_EMAIL";
export const CLEAR_VALID = "CLEAR_VALID";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const CLEAR_PASSWORD_CHANGE = "CLEAR_PASSWORD_CHANGE";

//PIN CODE
export const PIN_CODE_START = "PIN_CODE_START";
export const PIN_CODE_SUCCESS = "PIN_CODE_SUCCESS";
export const PIN_CODE_FAILURE = "PIN_CODE_FAILURE";

// profile

// ACTUALIZAR USUARIO
export const UPDATE_USER_START = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const GET_USER_PROFILE_DATA_START = "GET_USER_PROFILE_DATA_START";
export const GET_USER_PROFILE_DATA_SUCCESS = "GET_USER_PROFILE_DATA_SUCCESS";
export const GET_USER_PROFILE_DATA_FAILURE = "GET_USER_PROFILE_DATA_FAILURE";

// LOGOUT
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

// STYLE OF THE APP
export const MAIN_COLOR = "#DC200A";

// MAIN COLOR BUTTONS
export const BUTTON_MAIN_COLOR = "#679AFF";
export const BUTTON_SECONDARY_COLOR = "#0056FF";

// CLOSE ALERTS

export const CLOSE_ALERTS = "CLOSE_ALERTS";
export const CLOSE_ALERTS_TRANSFERENCIA = "CLOSE_ALERTS_TRANSFERENCIA";

// USER ENV
export const PROFILE_USER_START = "PROFILE_USER_START";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_FAILURE = "PROFILE_USER_FAILURE";

export const SEND_PIN_START = "PROFILE_USER_START";
export const SEND_PIN_SUCCESS = "PROFILE_USER_SUCCESS";
export const SEND_PIN_FAILURE = "PROFILE_USER_FAILURE";

// EDITAR USUARIO:
// TRANSFERENCIAS (CARGAR SALDO)
export const CARGAR_SALDO_USER_START = "CARGAR_SALDO_USER_START";
export const CARGAR_SALDO_USER_SUCCESS = "CARGAR_SALDO_USER_SUCCESS";
export const CARGAR_SALDO_USER_FAILURE = "CARGAR_SALDO_USER_FAILURE";

// TRANSFERENCIAS (CARGAR COTIZACIONES)
export const COTIZACIONES_START = "COTIZACIONES_START";
export const COTIZACIONES_SUCCESS = "COTIZACIONES_SUCCESS";
export const COTIZACIONES_FAILURE = "COTIZACIONES_FAILURE";

// TRANSFERENCIAS (ENVIAR TRANSFERENCIA)
export const ENVIAR_TRANSFERENCIA_START = "ENVIAR_TRANSFERENCIA_START";
export const ENVIAR_TRANSFERENCIA_SUCCESS = "ENVIAR_TRANSFERENCIA_SUCCESS";
export const ENVIAR_TRANSFERENCIA_FAILURE = "ENVIAR_TRANSFERENCIA_FAILURE";

export const OBTENER_INFO_USUARIO_START = "OBTENER_INFO_USUARIO_START";
export const OBTENER_INFO_USUARIO_SUCCESS = "OBTENER_INFO_USUARIO_SUCCESS";
export const OBTENER_INFO_USUARIO_FAILURE = "OBTENER_INFO_USUARIO_FAILURE";

// TRANSFERENCIAS
export const OBTENER_TRANSFERENCIAS_USUARIO_START =
  "OBTENER_TRANSFERENCIAS_USUARIO_START";
export const OBTENER_TRANSFERENCIAS_USUARIO_SUCCESS =
  "OBTENER_TRANSFERENCIAS_USUARIO_SUCCESS";
export const OBTENER_TRANSFERENCIAS_USUARIO_FAILURE =
  "OBTENER_TRANSFERENCIAS_USUARIO_FAILURE";

// RANDOMIZE THE LS STORE
// export const RANDOM_PHRASES_SET_LS = process.env.RANDOM_PHRASES_SET_LS;
// export const RANDOM_PHRASES_LS = process.env.RANDOM_PHRASES_LS;
